# Секция common: общие настройки для searchd и indexer
common {
    # Путь к словарям лемматизатора (.pak файлы)
    lemmatizer_base = /usr/share/manticore/
}

# Секция indexer: настройки инструмента индексации
indexer {
    # Кэш несжатого словаря. Для русского словаря (~110 МБ) 256M достаточно
    lemmatizer_cache = 256M
}

# Секция searchd: настройки демона
searchd {
    listen = 9306:mysql41
    listen = 9308:http
    listen = 9312:sphinx
    data_dir = /var/lib/manticore
    log = /var/log/manticore/searchd.log
    query_log = /var/log/manticore/query.log
    binlog_path = /var/lib/manticore/binlog
    pid_file = /var/run/manticore/searchd.pid
    auto_schema = 0 # определяет типы столбцов на основе предоставленных значений(включена по умолчанию)
    auth = 1
    auth_password_policy = MEDIUM
    auth_password_min_length = 16
    auth_log_level = info
}
